name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Generate content
      #  run:

      - name: Publish content
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: ./ay0ks.pl.eu.org
          target-branch: main-ay0ks.pl.eu.org
